In [ ]:
a = 2
b = 4
print(a+b)
print(a-b)
print(a/b)
print(a*b)

6
-2
0.5
8

In [ ]:
names = ["Aria", "Bhadra", "Chia"]
print(names)
print(names[2])
print(names[0:])
print(names[-1])

['Aria', 'Bhadra', 'Chia']
Chia
['Aria', 'Bhadra', 'Chia']
Chia

In [ ]:
def maths(a,b):
  return a + b
print(maths(67,54))

121

In [ ]:
import pandas as pd
data = { "name" : ["Aria", "Bhadra", "Chia"],
        "age" : [23, 45, 67],
         "hobbies" : ["singing", "drawing", "cycling"]}
x = pd.DataFrame(data)
#x.head()
x

     name  age  hobbies
0    Aria   23  singing
1  Bhadra   45  drawing
2    Chia   67  cycling

In [ ]:
import pandas as pd
print(pd.__version__)

2.2.2

In [ ]:
import pandas as pd
name = ["Aria", "Bhadra", "Chia"]
c = pd.Series(name, index=  ['x','y','z'])
c["y"]

'Bhadra'

In [ ]:
import pandas as pd
data = {"name1" : "Aria", "name2":"Bhadra", "name3":"Chia"}
x = pd.Series(data, index = ["name1", "name2"])
x

name1      Aria
name2    Bhadra
dtype: object

In [ ]:
import pandas as pd
data = { "name" : ["Aria", "Bhadra", "Chia"],
        "age" : [23, 45, 67],
         "hobbies" : ["singing", "drawing", "cycling"]}
x = pd.DataFrame(data, index = ["hobby1","hobby2","hobby3"])
print(x.loc["hobby1"])

name          Aria
age             23
hobbies    singing
Name: hobby1, dtype: object

In [ ]:
import pandas as pd
df = pd.read_csv("job_salary_prediction_dataset.csv")
#df.to_string()
df

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069
...,...,...,...,...,...,...,...,...,...,...
249995,Software Engineer,17,PhD,2,Telecom,Enterprise,India,No,1,127791
249996,Frontend Developer,20,PhD,7,Telecom,Startup,Remote,No,2,154593
249997,Business Analyst,1,Bachelor,12,Retail,Enterprise,India,Yes,0,75988
249998,Data Scientist,0,High School,2,Consulting,Small,Sweden,Hybrid,5,90467
249999,Data Analyst,16,Diploma,2,Technology,Medium,UK,No,5,133084